install.packages("tidyverse")
install.packages("cowplot")
install.packages("scatterpie")
install.packages("tinytex")
tinytex::install_tinytex()
tinytex::tlmgr_install(c(
    "fancyhdr",
    "multirow",
    "caption",
    "units",
    "microtype",
    "scalerel",
    "logreq",
    "biblatex-apa",
    "fp",
    "ms",
    "pgf"
))
