name: run

on: 
  pull_request:
    branches: 'master'
    paths-ignore: '.binder/**'
  push:
    branches: 'master'
    paths-ignore: '.binder/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start container
      run: |
        docker run -d --name repo-container ${{ secrets.DOCKER_USERNAME }}/sample-size-calculation-under-uncertainty
    - name: execute workflow
      run: |
        docker exec repo-container \
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 sample-size-calculation-under-uncertainty.ipynb
